# Base Centos7 with SSH and additional EPEL repo

FROM centos:7.2.1511

MAINTAINER Lucas Russo

RUN OPTNAMESERVER
    yum update -y && \
    yum install -y epel-release net-tools tar wget openssh-server openssh-clients passwd sudo
